export const interests = [
  { label: 'Music', value: 'Music' },
  { label: 'Sports', value: 'Sports' },
  { label: 'Technology', value: 'Technology' },
  { label: 'Art', value: 'Art' },
  { label: 'Books', value: 'Books' },
  { label: 'Cooking', value: 'Cooking' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Photography', value: 'Photography' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Movies', value: 'Movies' },
  { label: 'Fashion', value: 'Fashion' },
  { label: 'Nature', value: 'Nature' },
  { label: 'Programming', value: 'Programming' },
  { label: 'DIY', value: 'DIY' },
  { label: 'Health', value: 'Health' },
  { label: 'Science', value: 'Science' },
  { label: 'Pets', value: 'Pets' },
  { label: 'Food', value: 'Food' },
  { label: 'Cars', value: 'Cars' },
  { label: 'Politics', value: 'Politics' },
  { label: 'Education', value: 'Education' },
  { label: 'History', value: 'History' },
  { label: 'Finance', value: 'Finance' },
  { label: 'Design', value: 'Design' },
  { label: 'Animals', value: 'Animals' },
  { label: 'Psychology', value: 'Psychology' },
  { label: 'Business', value: 'Business' },
  { label: 'Sustainability', value: 'Sustainability' },
  { label: 'Yoga', value: 'Yoga' },
  { label: 'Dance', value: 'Dance' },
  { label: 'Fashion Design', value: 'Fashion Design' },
  { label: 'Cooking', value: 'Cooking' },
  { label: 'Outdoor Activities', value: 'Outdoor Activities' },
  { label: 'Interior Design', value: 'Interior Design' },
  { label: 'Writing', value: 'Writing' },
  { label: 'Reading', value: 'Reading' },
  { label: 'Painting', value: 'Painting' },
  { label: 'Drawing', value: 'Drawing' },
  { label: 'Sculpting', value: 'Sculpting' },
  { label: 'Board Games', value: 'Board Games' },
  { label: 'Video Editing', value: 'Video Editing' },
  { label: 'Graphic Design', value: 'Graphic Design' },
  { label: 'Web Development', value: 'Web Development' },
  { label: 'Mobile Apps Development', value: 'Mobile Apps Development' },
  { label: 'Data Science', value: 'Data Science' },
  { label: 'Machine Learning', value: 'Machine Learning' },
  { label: 'Artificial Intelligence', value: 'Artificial Intelligence' },
  { label: 'Blockchain', value: 'Blockchain' },
];
