import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ToastProvider } from './lib/contexts/providers/toast';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'You App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="portal"></div>
        <main id="RootLayout">
          <ToastProvider>{children}</ToastProvider>
        </main>
      </body>
    </html>
  );
}
